# Generated by Django 4.2.5 on 2023-11-07 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0002_resource_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='acquisition_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resource',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='resource',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='location',
            field=models.CharField(default='Location', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Liter'), ('unit', 'Unit'), ('box', 'Box'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(default='Resource Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('Food', 'Food'), ('Water', 'Water'), ('Medical Supplies', 'Medical Supplies'), ('Equipment', 'Equipment'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
