# Generated by Django 4.2.5 on 2023-11-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0006_remove_resource_acquisition_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='cost',
        ),
    ]
