# Generated by Django 4.2.5 on 2023-11-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0007_remove_resource_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='status',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='unit',
        ),
    ]
