# Generated by Django 4.2.5 on 2023-11-09 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0009_camp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='location_id',
        ),
    ]
