# Generated by Django 4.2.5 on 2023-11-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0012_camp_latitude_camp_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aidlink.coordinator'),
        ),
    ]
