# Generated by Django 4.2.5 on 2023-11-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0015_markedlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='longitude',
        ),
    ]
