# Generated by Django 4.2.5 on 2023-12-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0018_rename_sender_message_user_message_priority_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_admin_coordinators',
        ),
        migrations.AddField(
            model_name='resource',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
