# Generated by Django 4.2.5 on 2023-12-03 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0019_delete_add_admin_coordinators_resource_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('civilian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidlink.civilian')),
            ],
        ),
    ]
