# Generated by Django 4.2.5 on 2023-12-03 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0020_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='help_request_attachments/'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='confirmation_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='incident_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='language_preference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='people_affected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='relationship_to_situation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='special_needs',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='urgency_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='civilian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='request_type',
            field=models.CharField(max_length=50),
        ),
    ]
