# Generated by Django 4.2.5 on 2023-12-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0021_helprequest_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='request_status',
            field=models.PositiveIntegerField(choices=[(0, 'Request Sent'), (1, 'Request Received'), (2, 'Request Processing'), (3, 'Request Completed'), (4, 'Request Rejected')], default=0),
        ),
    ]
