# Generated by Django 4.2.5 on 2023-12-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0022_helprequest_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='request_status',
            field=models.IntegerField(choices=[(0, 'Request Sent'), (1, 'Request Received'), (2, 'Request Processing'), (3, 'Request Completed'), (4, 'Request Rejected')], default=0),
        ),
    ]
