# Generated by Django 4.2.5 on 2023-12-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0024_volunteerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='qualifications',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='qualities',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='volunteerrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
