# Generated by Django 4.2.5 on 2023-12-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0025_remove_volunteerrequest_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerrequest',
            old_name='qualifications',
            new_name='additional_information',
        ),
        migrations.RenameField(
            model_name='volunteerrequest',
            old_name='qualities',
            new_name='address',
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='agreement_and_code_of_conduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='areas_of_interest',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='availability_days_flexible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='availability_days_weekdays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='availability_days_weekends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='availability_for_deployment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='availability_times_afternoons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='availability_times_evenings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='availability_times_mornings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='background_check_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='certifications_cpr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='certifications_first_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='certifications_other',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='deployment_willingness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='driver_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='emergency_contact_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='emergency_contact_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='emergency_response_team_interest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='languages_spoken',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='media_release_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='other_considerations',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='phone_home',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='phone_mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='physical_limitations',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='previous_experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='references',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='relevant_skills_language_proficiency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='relevant_skills_logistics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='relevant_skills_medical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='relevant_skills_other',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='relevant_skills_technical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='volunteer_signatures/'),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='training_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='training_method_in_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='training_method_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='transportation_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerrequest',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
