# Generated by Django 4.2.5 on 2023-12-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0027_rename_additional_information_volunteerrequest_educational_qualifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='areas_of_interest',
        ),
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='deployment_willingness',
        ),
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='driver_license',
        ),
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='emergency_response_team_interest',
        ),
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='transportation_access',
        ),
    ]
