# Generated by Django 4.2.5 on 2023-12-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0030_volunteer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
