# Generated by Django 4.2.5 on 2024-02-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0032_manager_teamleader_teammember_user_is_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('OrgID', models.AutoField(primary_key=True, serialize=False)),
                ('OrgName', models.CharField(max_length=100)),
                ('OrgType', models.CharField(max_length=50)),
                ('ContactInfo', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
            ],
        ),
    ]
