# Generated by Django 4.2.5 on 2024-02-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0033_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='OrgID',
            new_name='OrganizationID',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='OrgName',
            new_name='OrganizationName',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='OrgType',
            new_name='OrganizationType',
        ),
    ]
