# Generated by Django 4.2.5 on 2024-02-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0034_rename_orgid_organization_organizationid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='aidlink.organization'),
        ),
    ]
