# Generated by Django 4.2.5 on 2024-02-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0037_user_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organization',
            new_name='organization_id',
        ),
    ]
