# Generated by Django 4.2.5 on 2024-02-09 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0038_rename_organization_user_organization_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization_id',
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='aidlink.organization'),
        ),
    ]
