# Generated by Django 4.2.5 on 2024-02-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0039_remove_user_organization_id_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
    ]
