# Generated by Django 4.2.5 on 2024-02-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0040_remove_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='aidlink.manager'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='aidlink.teamleader'),
        ),
    ]
