# Generated by Django 4.2.5 on 2024-02-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0041_teammember_manager_teammember_team_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team_leader',
        ),
    ]
