# Generated by Django 4.2.5 on 2024-02-22 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0042_remove_teammember_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization_Resources',
            fields=[
                ('ResourceID', models.AutoField(primary_key=True, serialize=False)),
                ('ResourceName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Quantity', models.IntegerField()),
                ('ResourceType', models.CharField(choices=[('Personnel', 'Personnel'), ('Equipment', 'Equipment'), ('Supplies', 'Supplies')], max_length=50)),
                ('OrgID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidlink.organization')),
            ],
        ),
    ]
