# Generated by Django 4.2.5 on 2024-02-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0043_organization_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization_resources',
            old_name='OrgID',
            new_name='OrganizationID',
        ),
    ]
