# Generated by Django 4.2.5 on 2024-02-29 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0045_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleader',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leaders', to='aidlink.manager'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='aidlink.teamleader'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, default='default@email.com', max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
