# Generated by Django 4.2.5 on 2024-02-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0048_task_assigned_to_delete_taskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
