# Generated by Django 4.2.5 on 2024-03-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0050_alertuserprofile_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertuserprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AlertUserProfile',
        ),
    ]
