# Generated by Django 4.2.5 on 2024-03-05 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0051_remove_alertuserprofile_user_delete_alert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('civilian', 'Civilian'), ('coordinator', 'Coordinator'), ('manager', 'Manager'), ('team_leader', 'Team Leader'), ('team_member', 'Team Member'), ('not_registered', 'Not a Registered User'), ('not_disclose', 'Not Interested in Disclosing User Type')], max_length=20)),
                ('feedback_text', models.TextField()),
                ('user_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('disclose_user_type', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
