# Generated by Django 4.2.5 on 2024-03-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0052_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_identifier',
        ),
    ]
