# Generated by Django 4.2.5 on 2024-03-05 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0053_remove_feedback_user_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_type',
            field=models.CharField(choices=[('civilian', 'Civilian'), ('coordinator', 'Coordinator'), ('manager', 'Manager'), ('team_leader', 'Team Leader'), ('team_member', 'Team Member'), ('unregistered', 'Not a Registered User'), ('no_disclosure', 'Not Interested in Disclosing User Type')], max_length=20),
        ),
    ]
