# Generated by Django 4.2.5 on 2024-03-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0056_alter_feedback_feedback_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_by',
        ),
    ]
