# Generated by Django 4.2.5 on 2024-03-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0059_donation_created_at_donation_name_donation_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
    ]
