# Generated by Django 4.2.5 on 2024-03-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0061_training_module_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='training',
        ),
        migrations.RemoveField(
            model_name='training',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
