# Generated by Django 4.2.5 on 2024-03-16 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0065_course_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to='aidlink.teamleader')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='aidlink.teammember')),
            ],
        ),
    ]
