# Generated by Django 4.2.5 on 2024-03-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0066_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
