# Generated by Django 4.2.5 on 2024-03-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0068_feedbackresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.IntegerField(default=0),
        ),
    ]
