# Generated by Django 4.2.5 on 2024-03-20 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0072_feedbackresponse_civilian_question1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
