# Generated by Django 4.2.5 on 2024-03-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0073_feedbackresponse_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, 'Civilian'), (2, 'Coordinator'), (3, 'Manager'), (4, 'Team Leader'), (5, 'Team Member'), (6, 'Unregistered'), (7, 'No Disclosure')])),
                ('question1', models.TextField()),
                ('question2', models.TextField()),
                ('question3', models.TextField()),
                ('question4', models.TextField()),
                ('question5', models.TextField()),
                ('question6', models.TextField()),
                ('question7', models.TextField()),
                ('question8', models.TextField()),
                ('question9', models.TextField()),
                ('question10', models.TextField()),
                ('feedback_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FeedbackResponse',
        ),
    ]
