# Generated by Django 4.2.5 on 2024-03-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0074_feedback_delete_feedbackresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('civilian', 'Civilian'), ('coordinator', 'Coordinator'), ('manager', 'Manager'), ('team_leader', 'Team Leader'), ('team_member', 'Team Member'), ('unregistered', 'Not a Registered User'), ('no_disclosure', 'Not Interested in Disclosing User Type')], max_length=50)),
                ('civilian_question1', models.TextField(blank=True)),
                ('civilian_question2', models.TextField(blank=True)),
                ('civilian_question3', models.TextField(blank=True)),
                ('civilian_question4', models.TextField(blank=True)),
                ('civilian_question5', models.TextField(blank=True)),
                ('civilian_question6', models.TextField(blank=True)),
                ('civilian_question7', models.TextField(blank=True)),
                ('civilian_question8', models.TextField(blank=True)),
                ('civilian_question9', models.TextField(blank=True)),
                ('civilian_question10', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
