# Generated by Django 4.2.5 on 2024-03-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0075_feedbackresponse_delete_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackresponse',
            old_name='civilian_question1',
            new_name='question1',
        ),
        migrations.RenameField(
            model_name='feedbackresponse',
            old_name='civilian_question10',
            new_name='question10',
        ),
        migrations.RenameField(
            model_name='feedbackresponse',
            old_name='civilian_question2',
            new_name='question2',
        ),
        migrations.RenameField(
            model_name='feedbackresponse',
            old_name='civilian_question3',
            new_name='question3',
        ),
        migrations.RenameField(
            model_name='feedbackresponse',
            old_name='civilian_question4',
            new_name='question4',
        ),
        migrations.RenameField(
            model_name='feedbackresponse',
            old_name='civilian_question5',
            new_name='question5',
        ),
        migrations.RenameField(
            model_name='feedbackresponse',
            old_name='civilian_question6',
            new_name='question6',
        ),
        migrations.RenameField(
            model_name='feedbackresponse',
            old_name='civilian_question7',
            new_name='question7',
        ),
        migrations.RenameField(
            model_name='feedbackresponse',
            old_name='civilian_question8',
            new_name='question8',
        ),
        migrations.RenameField(
            model_name='feedbackresponse',
            old_name='civilian_question9',
            new_name='question9',
        ),
    ]
