# Generated by Django 4.2.5 on 2024-03-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0077_damageassessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DamageAssessment',
        ),
    ]
