# Generated by Django 4.2.5 on 2024-04-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0078_delete_damageassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('assessment_result', models.CharField(max_length=255)),
            ],
        ),
    ]
