# Generated by Django 4.2.5 on 2024-04-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidlink', '0079_uploadedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
